.TH "VIMCAT" "1" "December 21, 2013" "vimcat user manual" ""
.SH NAME
.PP
vimcat \- vim based syntax highlighter
.SH SYNOPSIS
.PP
vimcat \f[I]some_file\f[]
.SH DESCRIPTION
.PP
cat\[aq]s a file to stdout, syntax\-highlighting it using vim as a
backend.
.PP
On GitHub: <http://github.com/rkitover/vimpager>
.PP
To use a different vimrc with vimcat, put your settings into a
~/.vimcatrc.
.PP
To disable loading plugins, put "set noloadplugins" into a ~/.vimcatrc
file.
.SH COMMAND LINE OPTIONS
.SS \-c cmd
.PP
Run a vim command after opening the file.
.SH LICENSE AND COPYRIGHT
.PP
Copyright (c) 2013, Rafael Kitover
.PP
Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions are
met:
.PP
Redistributions of source code must retain the above copyright notice,
this list of conditions and the following disclaimer.
.PP
Redistributions in binary form must reproduce the above copyright
notice, this list of conditions and the following disclaimer in the
documentation and/or other materials provided with the distribution.
.PP
THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDER ``AS IS\[aq]\[aq] AND
ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
PURPOSE ARE DISCLAIMED.
IN NO EVENT SHALL THE COPYRIGHT HOLDER BE LIABLE FOR ANY DIRECT,
INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
(INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT,
STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
POSSIBILITY OF SUCH DAMAGE.
.SH AUTHORS
Abdó Roig\-Maranges <abdo.roig@gmail.com>.
