.TH VIMCAT 1 "April 29, 2015" "vimcat user manual"
.SH NAME
.PP
vimcat - vim based syntax highlighter
.SH SYNOPSIS
.PP
vimcat \f[I]some_file\f[]
.SH DESCRIPTION
.PP
cat\[aq]s a file to stdout, syntax-highlighting it using vim as a
backend.
.PP
On GitHub: <http://github.com/rkitover/vimpager>
.PP
To use a different vimrc with vimcat, put your settings into a
~/.vimcatrc.
.PP
To disable loading plugins, put "set noloadplugins" into a ~/.vimcatrc
file.
.SH COMMAND LINE OPTIONS
.SS -c cmd
.PP
Run a vim command after opening the file.
Multiple -c arguments are supported.
.SS --cmd cmd
.PP
Run a vim command when entering vim before anything else.
Multiple --cmd arguments are supported.
.SS -u vimrc
.PP
Use an alternate .vimrc or .vimcatrc.
.SH AUTHORS
Abdó Roig-Maranges <abdo.roig@gmail.com>.
