.TH "VIMPAGER" "1" "November 24, 2013" "vimpager user manual" ""
.SH NAME
.PP
vimpager \- less.sh replacement
.SH SYNOPSIS
.PP
cat \f[I]some_file\f[] | vimpager
.SH DESCRIPTION
.PP
A slightly more sophisticated replacement for less.sh that also supports
being set as the PAGER environment variable.
Displays man pages, perldocs and python documentation properly.
Works on Linux, Solaris, FreeBSD, NetBSD, OpenBSD, OSX, Cygwin and msys.
Should work on most other systems as well.
.PP
On GitHub: <http://github.com/rkitover/vimpager>
.PP
To use it as as your PAGER: put these in your ~/.bashrc or ~/.zshrc
.IP
.nf
\f[C]
export\ PAGER=~/bin/vimpager
alias\ less=$PAGER
alias\ zless=$PAGER
\f[]
.fi
.PP
To use a different vimrc with vimpager, put your settings into a
~/.vimpagerrc or ~/.vim/vimpagerrc or a file pointed to by the
VIMPAGER_RC environment variable.
.PP
You can also have a global config file for all users in /etc/vimpagerrc,
users can override it by creating a ~/.vimpagerrc or a
~/.vim/vimpagerrc.
.PP
To disable loading plugins, put "set noloadplugins" into a vimpagerrc
file.
.PP
You can also switch on the "vimpager" variable in your vimrc to set
alternate settings for vimpager.
.PP
Put the following into your .vimrc/vimpagerrc if you want to use
gvim/MacVim for your pager window:
.IP
.nf
\f[C]
let\ vimpager_use_gvim\ =\ 1
\f[]
.fi
.PP
To pass through text that is smaller than the terminal height (without
highlighting, at present) use this:
.IP
.nf
\f[C]
let\ vimpager_passthrough\ =\ 1
\f[]
.fi
.PP
To start vim with \-X (no x11 connection, a bit faster startup) put the
following into your .vimrc/vimpagerrc:
.IP
.nf
\f[C]
let\ vimpager_disable_x11\ =\ 1
\f[]
.fi
.PP
The scroll offset (:help scrolloff), may be specified by placing the
following into your .vimrc/vimpagerrc (default = 5, disable = 0):
.IP
.nf
\f[C]
let\ vimpager_scrolloff\ =\ 5
\f[]
.fi
.PP
The process tree of vimpager is available in the "vimpager_ptree"
variable, an example usage is as follows:
.IP
.nf
\f[C]
if\ exists("vimpager")
\ \ if\ exists("vimpager_ptree")\ &&\ vimpager_ptree[\-2]\ ==\ \[aq]wman\[aq]
\ \ \ \ set\ ft=man
\ \ endif
endif
\f[]
.fi
.SH COMMAND LINE OPTIONS
.SS + | +G
.PP
Start at the end of the file, just like less.
.SS \-c cmd
.PP
Run a vim command after opening the file.
.SH CYGWIN NOTES
.PP
The Cygwin gvim is very buggy, vimpager works correctly with the native
Windows gvim, just put it in your PATH.
.SH LICENSE AND COPYRIGHT
.PP
Copyright (c) 2013, Rafael Kitover <rkitover@gmail.com>
.PP
Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions are
met:
.PP
Redistributions of source code must retain the above copyright notice,
this list of conditions and the following disclaimer.
.PP
Redistributions in binary form must reproduce the above copyright
notice, this list of conditions and the following disclaimer in the
documentation and/or other materials provided with the distribution.
.PP
THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDER ``AS IS\[aq]\[aq] AND
ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
PURPOSE ARE DISCLAIMED.
IN NO EVENT SHALL THE COPYRIGHT HOLDER BE LIABLE FOR ANY DIRECT,
INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
(INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT,
STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
POSSIBILITY OF SUCH DAMAGE.
.SH AUTHORS
Rafael Kitover <rkitover@gmail.com>.
