#!/bin/sh

# Add balancing end(if|for|while) statements for the shell code so it is parsed
# as vimscript correctly.

target="${1:-vimcat}"

rm -f "${target}.work"
# Write the shell code half up to current balancing statements.
awk '/^: end/ { exit } { print }' "${target}" >> "${target}.work"
# Create the balancing statements and write them.
awk '/^[ 	]*(if|for|while)/ { print $1 } /^: end/ { exit }' "${target}" \
    | sed '1!G;h;$!d' \
    | sed -e 's/^/: end/' >> "${target}.work"
# Last ": endif" to balance the beginning ": if 0"
echo ': endif' >> "${target}.work"
# Write out the second vimscript half after the balancing statements.
awk '
    !skip { print; next }
    /^: end/ { skip_block = 1; next }
    skip_block { skip = 0; print }
' skip=1 skip_block=0 "${target}" >> "${target}.work"
# Replace the file.
mv "${target}.work" "${target}"
chmod +x "${target}"
