#!/bin/sh

. inc/platform.sh

echo \
    bsd=$bsd \
    cygwin=$cygwin \
    freebsd=$freebsd \
    linux=$linux \
    msys=$msys \
    netbsd=$netbsd \
    openbsd=$openbsd \
    osx=$osx \
    solaris=$solaris \
    win32=$win32 \
    AWK=$AWK \
    SED=$SED \
    SED=$SED \
    HEAD_SYNTAX=$HEAD_SYNTAX \

# vim: sw=4 et tw=0:
