#!/bin/sh

. inc/platform.sh

# The backslash has to be put here 8 times: foctor two to get past the initial
# shell quoting, another factor two because it is used in the replacement
# string for sed, another factor two because the output of belows echo will be
# used in the replacement text in the sed call in the makefile.  This yields
# one backslash that can escape the single quote in the configured vimpager
# script.
AWK=$(echo "$AWK" | sed "s/'/'\\\\\\\\''/g")
SED=$(echo "$SED" | sed "s/'/'\\\\\\\\''/g")

echo \
    ${bsd:+bsd=$bsd} \
    ${cygwin:+cygwin=$cygwin} \
    ${freebsd:+freebsd=$freebsd} \
    ${linux:+linux=$linux} \
    ${msys:+msys=$msys} \
    ${netbsd:+netbsd=$netbsd} \
    ${openbsd:+openbsd=$openbsd} \
    ${osx:+osx=$osx} \
    ${solaris:+solaris=$solaris} \
    ${win32:+win32=$win32} \
    "AWK='$AWK'" \
    "SED='$SED'" \
    ${HEAD_SYNTAX:+HEAD_SYNTAX=$HEAD_SYNTAX} \

# vim: sw=4 et tw=0:
